spring.application.name=pizzariabemmelhor

# SQL Server Configuration

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=pizzariabemmelhordb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=@ITB123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Informações

# spring.jpa.hibernate.ddl-auto=
# none:    Banco de dados e tabelas devem ser criadas com antecedência
# update:  Banco de dados deve ser criado com antecedência, tabelas podem ser criadas com antecedência, entretanto,
#          as tabelas serão atualizadas pelo código JPA ( model )
# create-drop: Banco de dados deve ser criado com antecedência, as tabelas são criadas automaticamente pelo código (model),
#              entretanto, as tabelas serão excluídas toda vez que o servidor é "interrompido"
# create: Banco de dados deve ser criado com antecedência, quando o servidor carrega as tabelas são recriadas, entretanto,
#         quando o servidor é interrompido as tabelas permanecem


