package com.itb.inf3cm.pizzariabemmelhor.model.enums;


import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Permission {

    // FUNCIONARIO

    FUNCIONARIO_READ("FUNCIONARIO_READ"),
    FUNCIONARIO_UPDATE("FUNCIONARIO_UPDATE"),
    FUNCIONARIO_CREATE("FUNCIONARIO_CREATE"),
    FUNCIONARIO_DELETE("FUNCIONARIO_DELETE"),
    FUNCIONARIO_LIST("FUNCIONARIO_LIST"),
    FUNCIONARIO_MANAGE("FUNCIONARIO_MANAGE"),

    // CLIENTE

    CLIENTE_READ("CLIENTE_READ"),
    CLIENTE_UPDATE("CLIENTE_UPDATE"),
    CLIENTE_CREATE("CLIENTE_CREATE"),
    CLIENTE_DELETE("CLIENTE_DELETE"),
    CLIENTE_LIST("CLIENTE_LIST"),
    CLIENTE_MANAGE("CLIENTE_MANAGE"),

    // PEDIDO

    PEDIDO_READ("PEDIDO_READ"),
    PEDIDO_UPDATE("PEDIDO_UPDATE"),
    PEDIDO_CREATE("PEDIDO_CREATE"),
    PEDIDO_DELETE("PEDIDO_DELETE"),
    PEDIDO_LIST("PEDIDO_LIST"),
    PEDIDO_MANAGE("PEDIDO_MANAGE"),

    // CATEGORIA

    CATEGORIA_READ("CATEGORIA_READ"),
    CATEGORIA_UPDATE("CATEGORIA_UPDATE"),
    CATEGORIA_CREATE("CATEGORIA_CREATE"),
    CATEGORIA_DELETE("CATEGORIA_DELETE"),
    CATEGORIA_MANAGE("CATEGORIA_MANAGE"),

    // PRODUTO

    PRODUTO_READ("PRODUTO_READ"),
    PRODUTO_UPDATE("PRODUTO_UPDATE"),
    PRODUTO_CREATE("PRODUTO_CREATE"),
    PRODUTO_DELETE("PRODUTO_DELETE"),
    PRODUTO_MANAGE("PRODUTO_MANAGE");

    private final String permission;
}
